import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";

const genos = localFont({
    src: [
        {
            path: "../fonts/Genos/Genos-Medium.ttf",
            weight: "400",
            style: "normal",
        },

        {
            path: "../fonts/Genos/Genos-Regular.ttf",
            weight: "500",
            style: "normal",
        },
        {
            path: "../fonts/Genos/Genos-SemiBold.ttf",
            weight: "600",
            style: "normal",
        },
    ],
    variable: "--font-genos",
});

const dmSans = localFont({
    src: [
        {
            path: "../fonts/DMSans/DMSans-Regular.ttf",
            weight: "400",
            style: "normal",
        },
        {
            path: "../fonts/DMSans//DMSans-SemiBold.ttf",
            weight: "600",
            style: "normal",
        },
    ],
    variable: "--font-dmSans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = useMessages();
    return (
        <html lang={locale}>
            <NextIntlClientProvider locale={locale} messages={messages}>
                <body
                    className={`${dmSans.variable} ${genos.variable} antialiased`}
                >
                    <main>{children}</main>
                </body>
            </NextIntlClientProvider>
        </html>
    );
}
